import { Link } from 'react-router-dom';
import { BadgePoundSterling, BarChart3, Bell, CalendarDays, CheckCircle2, CircleAlert, Clock3, FileText, MessageSquare, ShieldCheck, Users } from 'lucide-react';
import { dashboardStats } from '../data/site';

export function LoginPage(){ return <section className="login-wrap"><div className="login-card"><div className="login-brand">5★</div><span className="eyebrow">PLATFORM PREVIEW</span><h1>Sign in to 5 Star Tuition</h1><p>Authentication will be connected before production. These buttons currently open safe demo dashboards.</p><div className="login-options"><Link to="/parent/dashboard" className="button button--navy">Parent / Student Demo</Link><Link to="/tutor/dashboard" className="button button--outline">Tutor Demo</Link><Link to="/admin/dashboard" className="button button--outline">Admin Demo</Link></div><small>Do not enter real customer data into the demo build.</small></div></section> }

const Stat = ({label,value}:{label:string;value:string}) => <div className="dash-stat"><span>{label}</span><strong>{value}</strong></div>;

export function ParentPortalPage(){ return <section className="portal-shell"><PortalTop title="Parent Portal"/><div className="portal-grid"><PortalSide active="Overview"/><div className="portal-main"><div className="portal-greeting"><div><span className="eyebrow">WELCOME BACK</span><h1>Student overview</h1><p>A future parent account will bring lessons, payments and progress into one place.</p></div><button className="button button--gold">Request support</button></div><div className="dash-stats"><Stat label="Upcoming lessons" value="3"/><Stat label="Homework tasks" value="2"/><Stat label="Progress reports" value="1"/><Stat label="Messages" value="4"/></div><div className="portal-columns"><div className="portal-panel"><div className="panel-title"><h3>Upcoming lessons</h3><CalendarDays/></div>{[['Mathematics','Tue 6:00 PM','Ayesha Khan'],['English','Thu 5:30 PM','Mariam Ali'],['Mathematics','Tue 6:00 PM','Ayesha Khan']].map(x=><div className="lesson-row" key={x.join()}><div><strong>{x[0]}</strong><span>{x[2]}</span></div><b>{x[1]}</b></div>)}</div><div className="portal-panel"><div className="panel-title"><h3>Progress snapshot</h3><BarChart3/></div><div className="grade-progress"><div><span>Current grade</span><strong>5</strong></div><i>→</i><div><span>Target grade</span><strong>8</strong></div></div><div className="progress-track"><i style={{width:'68%'}}/></div><small>Demo data only</small></div></div></div></div></section> }

export function TutorPortalPage(){ return <section className="portal-shell"><PortalTop title="Tutor Portal"/><div className="portal-grid"><PortalSide active="Overview"/><div className="portal-main"><div className="portal-greeting"><div><span className="eyebrow">TUTOR WORKSPACE</span><h1>Your teaching week</h1><p>Future tutors will manage students, lesson notes, availability and earnings here.</p></div><button className="button button--gold">Update availability</button></div><div className="dash-stats"><Stat label="Students" value="8"/><Stat label="Lessons this week" value="14"/><Stat label="Pending notes" value="2"/><Stat label="Pending earnings" value="£280"/></div><div className="portal-columns"><div className="portal-panel"><div className="panel-title"><h3>Today</h3><Clock3/></div>{[['4:30 PM','Year 9 Computer Science'],['6:00 PM','Year 11 GCSE Maths'],['7:15 PM','Year 12 A-Level Maths']].map(x=><div className="lesson-row" key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><div className="portal-panel"><div className="panel-title"><h3>Actions required</h3><Bell/></div><div className="action-row"><CircleAlert/> Submit lesson note for Adam</div><div className="action-row"><CircleAlert/> Confirm next month availability</div><div className="action-row good"><CheckCircle2/> Contract active</div></div></div></div></div></section> }

export function AdminPortalPage(){ return <section className="portal-shell admin-portal"><PortalTop title="Admin Portal"/><div className="portal-grid"><PortalSide active="Dashboard" admin/><div className="portal-main"><div className="portal-greeting"><div><span className="eyebrow">OPERATIONS</span><h1>5 Star Tuition dashboard</h1><p>One operational view for enquiries, tutors, trials, students and money.</p></div><button className="button button--gold">+ New record</button></div><div className="dash-stats">{dashboardStats.map(([a,b])=><Stat key={a} label={a} value={b}/>)}</div><div className="admin-alerts"><div><CircleAlert/><strong>4</strong><span>overdue payments</span></div><div><Clock3/><strong>7</strong><span>trials awaiting outcome</span></div><div><FileText/><strong>3</strong><span>tutor documents missing</span></div><div><Users/><strong>14</strong><span>new enquiries</span></div></div><div className="portal-panel"><div className="panel-title"><h3>Students awaiting action</h3><ShieldCheck/></div><div className="data-table"><div className="data-head"><span>Student</span><span>Request</span><span>Status</span><span>Action</span></div>{[['Adam R.','Year 11 Maths','Tutor search'],['Sara K.','11+ English & Maths','Trial booked'],['Yusuf A.','A-Level Physics','Awaiting payment'],['Layla M.','GCSE Chemistry','Tutor proposed']].map(x=><div className="data-row" key={x[0]}><span><strong>{x[0]}</strong></span><span>{x[1]}</span><span><b className="status-pill">{x[2]}</b></span><span><button>Open</button></span></div>)}</div></div></div></div></section> }

function PortalTop({title}:{title:string}){return <div className="portal-top"><Link to="/" className="mini-brand"><span>5★</span><strong>5 STAR TUITION</strong></Link><div><span>{title}</span><Link to="/">Exit demo</Link></div></div>}
function PortalSide({active,admin=false}:{active:string;admin?:boolean}){const links=admin?['Dashboard','Enquiries','Students','Tutors','Trials','Lessons','Payments','Reports','Messages','Settings']:['Overview','Calendar','Lessons','Progress','Payments','Files','Messages','Support'];return <aside className="portal-side">{links.map(x=><button className={x===active?'active':''} key={x}>{x}</button>)}</aside>}
