import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BadgeCheck, CalendarCheck2, CheckCircle2, Globe2, GraduationCap, MessageCircle, ShieldCheck, Sparkles, Target, Users } from 'lucide-react';
import { PageHero, SectionHeading } from '../components/Ui';

const bullets=(items:string[]) => <div className="check-stack">{items.map(x=><span key={x}><CheckCircle2/> {x}</span>)}</div>;

export function CurriculaPage(){return <><PageHero eyebrow="CURRICULA" title="UK and international curricula, matched properly." text="Tutor profiles record level, curriculum and exam-board experience so matching is specific to what the student is actually studying." cta="Find My Tutor"/><section className="section shell"><div className="curriculum-grid">{['UK National Curriculum','AQA','Pearson Edexcel','OCR','WJEC / Eduqas','Cambridge International','GCSE','IGCSE','A-Level','International A-Level','IB','AP'].map(x=><article key={x}><GraduationCap/><h3>{x}</h3><p>Subject-specific support with curriculum-aware teaching and exam preparation where applicable.</p></article>)}</div></section></>}

export function ParentsPage(){return <><PageHero eyebrow="FOR PARENTS" title="Clear support from first enquiry to regular tuition." text="You are not simply handed a tutor’s phone number. We manage matching, the initial trial, scheduling support and the ongoing tuition relationship." cta="Find My Tutor"/><section className="section shell"><div className="cards-2"><article className="content-card"><ShieldCheck/><h3>Vetted tutors</h3><p>Tutors are reviewed by our team before they become available for matching.</p></article><article className="content-card"><Target/><h3>Personal matching</h3><p>Subject, level, curriculum, availability and tutor preferences are considered together.</p></article><article className="content-card"><CalendarCheck2/><h3>Flexible scheduling</h3><p>Regular tuition is arranged around suitable student and tutor availability.</p></article><article className="content-card"><MessageCircle/><h3>Ongoing support</h3><p>5 Star Tuition remains involved when timetables, payments or arrangements need attention.</p></article></div></section><section className="section section--mist"><div className="shell split-grid"><SectionHeading eyebrow="WHAT TO EXPECT" title="A professional parent experience." text="The platform is being designed so parents can eventually manage upcoming lessons, packages, invoices, progress reports, homework and messages from one secure account."/><div>{bullets(['Free 30-minute initial trial','Transparent hourly pricing','2, 4 or 8-week starter package','Minimum 4-week package from second payment onwards','Progress and lesson records as the portal expands'])}</div></div></section></>}

export function TutorsInfoPage(){return <><PageHero eyebrow="FOR TUTORS" title="Teach through a platform that values quality and professionalism." text="We match approved tutors with suitable students, manage the commercial relationship and provide a structured route for ongoing tuition."/><section className="section shell split-grid"><div><SectionHeading eyebrow="APPLICATION" title="Our tutor approval process." text="Applications are reviewed before a tutor is activated for student matching."/>{bullets(['Application and teaching profile','Personal vetting call with 5 Star Tuition','Qualifications and experience reviewed','References/testimonials where required','Tutor agreement completed before activation'])}<Link to="/become-a-tutor" className="button button--gold">Apply to Tutor <ArrowRight size={16}/></Link></div><div className="info-panel"><BadgeCheck/><h3>What we record</h3><p>Subjects · Key Stages · curricula · exam boards · qualifications · classroom experience · tutoring experience · current role · location · availability · expected rate.</p></div></section></>}

export function ReviewsPage(){return <><PageHero eyebrow="REVIEWS" title="Parent feedback will be published transparently." text="Only genuine 5 Star Tuition feedback should appear on the live website. Demo testimonials used during development will be replaced before launch."/><section className="section shell"><div className="trust-card"><Sparkles/><h2>Verified feedback area</h2><p>Once your existing testimonials are supplied, this page will organise them by tuition level and service, with consent recorded before publication.</p></div></section></>}

export function FaqPage(){const q=[['How does the free trial work?','We arrange a 30-minute introductory trial with the proposed tutor. A 5 Star Tuition team member attends the initial trial.'],['How do you choose a tutor?','We compare the student’s subject, level, curriculum, availability, goals and preferences against approved tutor profiles, then a team member confirms the match.'],['How do tuition packages work?','New students can begin with a 2, 4 or 8-week package. From the second payment onwards, the minimum commitment is 4 weeks.'],['What happens if we need to rearrange?','With at least 24 hours’ notice, we normally try to rearrange the lesson within the same week where possible.'],['Is tuition online?','Yes. 5 Star Tuition is online-only at present and supports students internationally.'],['What ages do you support?','Core school tuition runs from Year 3 to Year 13, alongside entrance exams, admissions tests, university applications and selected adult/external preparation.']];return <><PageHero eyebrow="FAQS" title="Straight answers to common questions." text="Everything parents and students should know before starting."/><section className="section shell faq-list">{q.map(([a,b])=><details key={a}><summary>{a}</summary><p>{b}</p></details>)}</section></>}

export function ContactPage(){return <><PageHero eyebrow="CONTACT" title="Tell us what support you need." text="For a tutor request, the Find My Tutor form is the fastest route. For general questions, contact the team directly."/><section className="section shell contact-grid"><div className="contact-card"><MessageCircle/><h3>WhatsApp</h3><p>Current contact while the dedicated business number is being prepared.</p><a className="button button--navy" href="https://wa.me/447983452340">Message +44 79 8345 2340</a></div><div className="contact-card"><Globe2/><h3>Worldwide online tuition</h3><p>Priority markets: UK, UAE, Qatar, Bahrain and Saudi Arabia, with tuition available worldwide.</p><Link className="button button--gold" to="/find-a-tutor">Find My Tutor</Link></div></section></>}

function PolicyPage({eyebrow,title,intro,children}:{eyebrow:string;title:string;intro:string;children:ReactNode}){return <><PageHero eyebrow={eyebrow} title={title} text={intro}/><section className="section shell policy-page">{children}</section></>}
export function SafeguardingPage(){return <PolicyPage eyebrow="SAFEGUARDING" title="A safe, professional online tuition environment." intro="Safeguarding processes will be formalised before the production platform accepts live student accounts."><h2>Our approach</h2><p>Tutor vetting, appropriate communication, parent/guardian involvement for minors, access controls and clear reporting procedures form part of the production launch requirements.</p><h2>Before launch</h2>{bullets(['Final safeguarding policy reviewed','Tutor checks recorded appropriately by jurisdiction','Clear reporting route for parents, students and tutors','Role-based access to student information','Online lesson conduct requirements'])}</PolicyPage>}
export function PrivacyPage(){return <PolicyPage eyebrow="PRIVACY" title="Privacy and data protection." intro="This development copy is not a substitute for the final legally reviewed privacy notice."><h2>Data we expect to process</h2><p>Parent contact information, student tuition requirements, tutor professional information, lesson records, package/payment records and platform activity required to provide the service.</p><h2>Production requirement</h2><p>Before real customer data is collected, the final privacy notice, retention rules, lawful bases, security controls and international processing arrangements must be confirmed.</p></PolicyPage>}
export function TermsPage(){return <PolicyPage eyebrow="TERMS" title="Parent and student terms." intro="The commercial rules already agreed will be converted into final terms before launch."><h2>Core package structure</h2><p>New customers may start with a 2, 4 or 8-week package. From the second payment onwards the minimum commitment is 4 weeks.</p><h2>Important</h2><p>The live terms should be professionally reviewed before the production platform accepts payments.</p></PolicyPage>}
export function CancellationPolicyPage(){return <PolicyPage eyebrow="CANCELLATIONS & REFUNDS" title="Flexible where possible, clear when lessons are missed." intro="We aim to handle genuine changes reasonably while protecting tutor time and scheduled tuition."><h2>Rescheduling</h2><p>With 24+ hours’ notice, the session will normally be rearranged within the same week where possible.</p><h2>Missed lessons without sufficient notice</h2>{bullets(['First occurrence: warning only','Second occurrence: 50% of lesson time forfeited; for a one-hour lesson, up to 30 minutes may be added to a future lesson','Third occurrence: full lesson forfeited','Repeated non-attendance may result in tuition being discontinued'])}<h2>Tutor cancellation</h2><p>Tutors should provide at least 48 hours’ notice. Students do not lose paid tuition because a tutor cancels.</p><h2>Package refunds</h2><p>For the first package, unused sessions are refundable pro rata using the actual/package-discounted rate paid. From the second package onwards, the refund is the lower of the unused-session value or 50% of the original package purchase price.</p></PolicyPage>}
