import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, BadgeCheck, CalendarDays, CheckCircle2, FileText, Filter, GraduationCap, Search, ShieldCheck, Sparkles, Target, Users } from 'lucide-react';
import { PageHero, SectionHeading, TutorCard } from '../components/Ui';
import { pricing, subjects, tutors } from '../data/site';

export function TuitionPage() {
  const stages = [
    ['Primary tuition','Years 3–6','Core Maths, English and wider curriculum support designed to strengthen confidence and foundations.'],
    ['Secondary tuition','Years 7–9','Subject-specific tuition that develops independence and prepares students for GCSE pathways.'],
    ['GCSE / IGCSE','Years 10–11','Exam-board aware tuition, targeted revision, past-paper work and grade-focused support.'],
    ['A-Level / IB','Years 12–13','Advanced subject tuition, deeper understanding and examination preparation for sixth form.'],
  ];
  return <><PageHero eyebrow="SCHOOL TUITION" title="Personalised tuition from Year 3 to Year 13." text="One-to-one online tuition across UK and international curricula, matched around the student’s goals, level and preferred learning style." cta="Find My Tutor"/><section className="section shell"><div className="cards-2">{stages.map(([t,m,d])=><article className="content-card" key={t}><span>{m}</span><h3>{t}</h3><p>{d}</p><Link to="/find-a-tutor">Request a tutor <ArrowRight size={16}/></Link></article>)}</div></section><section className="section section--mist"><div className="shell"><SectionHeading eyebrow="CURRICULA" title="UK and international pathways." text="We record curriculum and exam-board expertise as part of every tutor profile so your match can be specific rather than generic."/><div className="tag-cloud">{['UK National Curriculum','AQA','Pearson Edexcel','OCR','WJEC / Eduqas','Cambridge International','GCSE','IGCSE','A-Level','International A-Level','IB','AP'].map(x=><span key={x}>{x}</span>)}</div></div></section></>;
}

export function SubjectsPage() { return <><PageHero eyebrow="SUBJECT DIRECTORY" title="Find support for the subject your student needs." text="Browse our core subject areas. If your subject is not listed, submit an enquiry and we’ll check our tutor network."/><section className="section shell"><div className="subject-directory">{subjects.map((s,i)=><Link to={`/subjects/${s.toLowerCase().replaceAll(' ','-')}`} key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong><small>Explore tuition</small><ArrowRight/></Link>)}</div></section></> }

export function SubjectDetailPage(){ const { slug='subject' }=useParams(); const name=slug.split('-').map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' '); return <><PageHero eyebrow="SUBJECT TUITION" title={`${name} tuition, matched to the student.`} text={`Personalised online ${name} tuition across school levels, exam boards and international curricula.`} cta={`Find a ${name} Tutor`}/><section className="section shell split-grid"><div><SectionHeading eyebrow="WHAT WE FOCUS ON" title="A clear plan built around the student." text="The tutor can target gaps, strengthen subject knowledge, improve exam technique and keep work aligned with the student’s school or exam-board requirements."/><div className="check-stack">{['Current level and target outcome','Curriculum and exam board','Topic gaps and misconceptions','Exam technique and past-paper skills','Confidence, independence and study habits'].map(x=><span key={x}><CheckCircle2/> {x}</span>)}</div></div><div className="info-panel"><h3>Typical matching information</h3><p>Year group · curriculum · exam board · current grade · target grade · availability · tutor preferences.</p><Link to="/find-a-tutor" className="button button--gold">Start a free trial</Link></div></section></> }

export function ExamsAdmissionsPage(){ const groups=[['School entrance','7+, 8+, 11+, 13+, ISEB, Common Entrance, CAT4, UKiset'],['University tests','UCAT, LNAT, TMUA, ESAT, TARA'],['International exams','SAT, ACT, AP, IELTS, TOEFL, PTE, OET'],['Applications & interviews','Oxbridge, Medicine / Dentistry, MMI, university interviews, UCAS, personal statements, US college applications']]; return <><PageHero eyebrow="EXAMS & ADMISSIONS" title="Preparation for competitive exams and applications." text="Specialist online support for school entrance, admissions tests, international exams, interviews and university applications." cta="Request a Specialist Tutor"/><section className="section shell"><div className="cards-2">{groups.map(([t,d])=><article className="content-card" key={t}><Sparkles/><h3>{t}</h3><p>{d}</p><Link to="/find-a-tutor">Find specialist support <ArrowRight size={16}/></Link></article>)}</div></section></> }

export function HowItWorksPage(){ const steps=[['1','Tell us what you need','Complete the tutor request form with subject, level, goals, availability and tutor preferences.'],['2','We shortlist suitable tutors','The system helps surface tutors whose expertise and availability align with the request. A 5 Star Tuition team member approves the match.'],['3','Take a free 30-minute trial','A member of our team attends the initial trial to introduce everyone and ensure the match feels right.'],['4','Choose your package','New students can begin with 2, 4 or 8 weeks. From the second payment onwards, the minimum commitment is 4 weeks.'],['5','Continue with ongoing support','We remain involved with scheduling, progress, payments and any changes needed during the tuition relationship.']]; return <><PageHero eyebrow="HOW IT WORKS" title="A managed tuition service, not just a tutor listing." text="We stay involved from the first enquiry through matching, trial, payment and ongoing support."/><section className="section shell"><div className="timeline">{steps.map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section></> }

export function PricingPage(){ const [hours,setHours]=useState(1); const [weeks,setWeeks]=useState(4); const [level,setLevel]=useState('GCSE / IGCSE'); const rate=Number((pricing.find(x=>x[0]===level)?.[1] || '£45').replace(/[^0-9]/g,'')); const total=rate*hours*weeks; return <><PageHero eyebrow="PRICING" title="Straightforward pricing with a free initial trial." text="Hourly rates are transparent. Package totals depend on lesson frequency and the number of weeks selected."/><section className="section shell"><div className="pricing-grid pricing-grid--large">{pricing.map(([name,price])=><div className="price-card" key={name}><span>{name}</span><strong>{price}</strong><small>per 60-minute lesson</small></div>)}</div><div className="calculator"><div><span className="eyebrow">PACKAGE CALCULATOR</span><h2>Estimate a tuition package.</h2><p>This calculator is for planning only; final package details are confirmed after the trial.</p></div><div className="calc-fields"><label>Level<select value={level} onChange={e=>setLevel(e.target.value)}>{pricing.map(x=><option key={x[0]}>{x[0]}</option>)}</select></label><label>Lessons per week<select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label><label>Package<select value={weeks} onChange={e=>setWeeks(Number(e.target.value))}><option value="2">2 weeks</option><option value="4">4 weeks</option><option value="8">8 weeks</option></select></label><div className="calc-total"><span>Estimated total</span><strong>£{total}</strong></div></div></div></section></> }

export function TutorsPage(){ const [query,setQuery]=useState(''); const [subject,setSubject]=useState('All'); const filtered=useMemo(()=>tutors.filter(t=>(subject==='All'||t.subjects.includes(subject))&&(t.name.toLowerCase().includes(query.toLowerCase())||t.subjects.join(' ').toLowerCase().includes(query.toLowerCase()))),[query,subject]); return <><PageHero eyebrow="TUTOR DIRECTORY" title="Meet tutors from our approved network." text="The live platform will show only tutors who have completed 5 Star Tuition vetting and are currently available for matching."/><section className="section shell"><div className="filter-bar"><div className="searchbox"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by tutor or subject"/></div><div className="filter-select"><Filter/><select value={subject} onChange={e=>setSubject(e.target.value)}><option>All</option>{subjects.slice(0,12).map(s=><option key={s}>{s}</option>)}</select></div></div><div className="tutor-grid tutor-grid--4">{filtered.map(t=><TutorCard key={t.id} tutor={t}/>)}</div>{filtered.length===0&&<div className="empty-state">No demo tutors match those filters. In production, this will search the live approved tutor database.</div>}</section></> }

export function TutorProfilePage(){ const {id}=useParams(); const tutor=tutors.find(t=>String(t.id)===id)||tutors[0]; return <><section className="profile-hero"><div className="shell profile-grid"><div className="profile-avatar">{tutor.initials}</div><div><span className="verified"><BadgeCheck size={16}/> Verified tutor</span><h1>{tutor.name}</h1><p className="profile-title">{tutor.title}</p><div className="tag-row">{tutor.subjects.map(s=><span key={s}>{s}</span>)}</div><p>{tutor.bio}</p><Link to="/find-a-tutor" className="button button--gold">Request a Free Trial</Link></div><aside><strong>{tutor.rating}/5</strong><span>{tutor.reviews} demo reviews</span><hr/><b>{tutor.experience}</b><small>{tutor.availability}</small><small>{tutor.levels.join(' · ')}</small></aside></div></section><section className="section shell"><div className="cards-2"><article className="content-card"><h3>Teaching approach</h3><p>Structured, student-centred tuition with clear lesson goals, regular retrieval and targeted practice.</p></article><article className="content-card"><h3>Matching notes</h3><p>Availability, exam-board experience and student preferences are checked before a trial is proposed.</p></article></div></section></> }

export function AboutPage(){ return <><PageHero eyebrow="ABOUT 5 STAR TUITION" title="A more personal way to arrange online tuition." text="5 Star Tuition manages the relationship from tutor matching and trial through to scheduling, payments and ongoing support."/><section className="section shell split-grid"><div><SectionHeading eyebrow="OUR APPROACH" title="Quality control stays human." text="Technology should make tuition easier to organise, but tutor quality and student fit still need careful judgement. Our platform is being designed to support that process — not replace it."/></div><div className="values-grid"><div><ShieldCheck/><h3>Vetted</h3><p>Tutors are personally reviewed before approval.</p></div><div><Target/><h3>Focused</h3><p>Matching starts with the student’s actual requirements.</p></div><div><Users/><h3>Supported</h3><p>We remain involved after the initial introduction.</p></div><div><GraduationCap/><h3>Academic</h3><p>Built for school tuition, exams and admissions.</p></div></div></section></> }

export function ResourcesPage(){ return <><PageHero eyebrow="RESOURCES" title="Useful guidance for students and parents." text="This area is ready for revision guides, exam-board articles, admissions explainers and downloadable study resources."/><section className="section shell"><div className="resource-grid">{['Choosing the right GCSE tutor','How to prepare for an 11+ trial lesson','GCSE revision planning','A-Level study habits','UCAT preparation timeline','Understanding international curricula'].map((x,i)=><article key={x}><div className="resource-icon"><FileText/></div><span>GUIDE {String(i+1).padStart(2,'0')}</span><h3>{x}</h3><p>Editorial content placeholder for the future 5 Star Tuition resources hub.</p><a href="#">Read guide <ArrowRight size={15}/></a></article>)}</div></section></> }

export function NotFoundPage(){ return <section className="section shell center"><h1>Page not found</h1><p>The page you’re looking for is not available.</p><Link className="button button--gold" to="/">Return home</Link></section> }
